"""initial clean

Revision ID: 91e9fc5f3af9
Revises: 
Create Date: 2025-06-18 01:31:02.786252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91e9fc5f3af9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('summary', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('summary'),
    sa.UniqueConstraint('title')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('illustration', sa.VARCHAR(length=500), nullable=True),
    sa.Column('status', postgresql.ENUM('PLANNING', 'IN_PROGRESS', 'COMPLETED', name='projectstatus'), nullable=False),
    sa.Column('github_link', sa.VARCHAR(length=500), nullable=True),
    sa.Column('website_link', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('title')
    )
    op.create_table('resume',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('resume_link', sa.VARCHAR(length=500), nullable=True),
    sa.Column('views_counter', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', postgresql.ENUM('PROGRAMMING_LANGUAGES', 'FRONTEND', 'BACKEND', 'DATABASE', 'DEVOPS', 'TOOLS', name='category_enum'), nullable=False),
    sa.Column('years_of_experience', sa.INTEGER(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('skill_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project_skill',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_skill')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('resume')
    op.drop_table('projects')
    op.drop_table('posts')
    # ### end Alembic commands ###
