"""remove project_skill table

Revision ID: d90277af47c7
Revises: 889d832bd503
Create Date: 2025-06-20 18:03:31.970463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90277af47c7'
down_revision: Union[str, None] = '889d832bd503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_skill')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_skill',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('project_skill_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], name=op.f('project_skill_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'skill_id', name=op.f('project_skill_pkey'))
    )
    # ### end Alembic commands ###
